const imagesinfo=[
    {id:1,path:'../Images/AlmondCookie.jpeg',name:'Almond Cookie',price:'350',type:'Biscuit',egg:0},
    {id:2,path:'../Images/Brookie.jpeg',name:'Brookie',price:'350',type:'Biscuit',egg:0},
    {id:3,path:'../Images/Karachi.jpeg',name:'Karachi Cookie',price:'250',type:'Biscuit',egg:0},
    {id:4,path:'../Images/NutellaCookie.jpeg',name:'Nutella Cookie',price:'350',type:'Biscuit',egg:0},
    {id:5,path:'../Images/ButterCookie.jpeg',name:'Butter Cookie',price:'250',type:'Biscuit',egg:0},
    {id:6,path:'../Images/ChocolateCookie.jpeg',name:'Chocolate Cookie',price:'250',type:'Biscuit',egg:1},
    {id:7,path:'../Images/AlmondChocolate.jpeg',name:'Almond Chocolate',price:'300',type:'Chocolate',egg:0},
    {id:8,path:'../Images/HazelnutChocolate.jpeg',name:'Hazelnut Chocolate',price:'400',type:'Chocolate',egg:0},
    {id:9,path:'../Images/PlainChocolate.jpg',name:'Plain Chocolate',price:'200',type:'Chocolate',egg:0},
    {id:10,path:'../Images/CustomisedChocolate.jpeg',name:'Caramel Chocolate',price:'250',type:'Chocolate',egg:0},
    {id:11,path:'../Images/ChocolateIcecream.jpeg',name:'Chocolate Icecream',price:'500',type:'Icecream'},
    {id:12,path:'../Images/OrangeIcecream.jpeg',name:'Orange Icecream',price:'500',type:'Icecream'},
    {id:12,path:'../Images/OrangeIcecream.jpeg',name:'Strawberry Icecream',price:'500',type:'Icecream'},
    {id:12,path:'../Images/OrangeIcecream.jpeg',name:'Oreo Icecream',price:'500',type:'Icecream'},
    {id:12,path:'../Images/OrangeIcecream.jpeg',name:'Tender Coconut Icecream',price:'700',type:'Icecream'},
    {id:13,path:'../Images/ButterscotchIcecream.jpeg',name:'Buttter Scotch',price:'500',type:'Icecream'},
    {id:14,path:'../Images/BlueberryIcecream.jpeg',name:'Blueberry Icecream',price:'500',type:'Icecream'},
    {id:15,path:'../Images/GuavaIcecream.jpeg',name:'Guava Icecream',price:'600',type:'Icecream'},
    {id:16,path:'../Images/SapotaIcecream.jpeg',name:'Sapota Icecream',price:'600',type:'Icecream'},
    {id:16,path:'../Images/SapotaIcecream.jpeg',name:'Mango Icecream',price:'700',type:'Icecream'},
    {id:17,path:'../Images/CustardappleIcecream.jpeg',name:'Custard Apple Icecream',price:'700',type:'Icecream'},
    {id:18,path:'../Images/ChocolatePastry.jpeg',name:'Chocolate Pastry',price:'500',type:'Pastry'},
    {id:19,path:'../Images/TrufflePastry.jpeg',name:'Truffle Pastry',price:'600',type:'Pastry'},
    {id:20,path:'../Images/OrangePastry.jpeg',name:'Orange Pastry',price:'500',type:'Pastry'},
    {id:21,path:'../Images/PineapplePastry.jpeg',name:'Pineapple Pastry',price:'500',type:'Pastry'},
    {id:22,path:'../Images/StrawberryPastry.jpeg',name:'Strawbeery Pastry',price:'500',type:'Pastry'},
    {id:24,path:'../Images/MangoPastry.jpeg',name:'Mango Pastry',price:'500',type:'Pastry'},
    {id:25,path:'../Images/ButterscotchPastry.jpeg',name:'Butterscotch Pastry',price:'600',type:'Pastry'},
    {id:26,path:'../Images/RedvelvetPastry.jpeg',name:'Red Velvet Pastry',price:'600',type:'Pastry'},
    {id:29,path:'../Images/BlueberryPastry.jpeg',name:'Blueberry Pastry',price:'600',type:'Pastry'},
    {id:30,path:'../Images/ChocolateCupcake.jpeg',name:'Chocolate Cupcake',price:'60',type:'Cupcake'},
    {id:31,path:'../Images/StrawberryCupcake.jpeg',name:'Strawberry Cupcake',price:'60',type:'Cupcake'},
    {id:32,path:'../Images/PineappleCupcake.jpeg',name:'Pineapple Cupcake',price:'60',type:'Cupcake'},
    {id:33,path:'../Images/OrangeCupcake.jpeg',name:'Ornage Cupcake',price:'60',type:'Cupcake'},
    {id:34,path:'../Images/MangoCupcake.jpeg',name:'Mango Cupcake',price:'60',type:'Cupcake'},
    {id:35,path:'../Images/ButterscotchCupcake.jpeg',name:'Butter scotch Cupcake',price:'60',type:'Cupcake'},
    {id:36,path:'../Images/RedvelvetCupcake.jpeg',name:'Red Velvet Cupcake',price:'60',type:'Cupcake'},
    {id:38,path:'../Images/BlueberryCupcake.jpeg',name:'Blueberry Cupcake',price:'60',type:'Cupcake'},
    {id:39,path:'../Images/BrowniesCake.jpeg',name:'Brownies',price:'700',type:'Cake'},
    {id:40,path:'../Images/StrawberryPlaincake.jpeg',name:'Strawberry Plain Cake',price:'400',type:'Cake'},
    {id:41,path:'../Images/OrangePlaincake.jpeg',name:'Orange Plain Cake',price:'400',type:'Cake'},
    {id:42,path:'../Images/BlueberryPlaincake.jpeg',name:'Blueberry Plain Cake',price:'400',type:'Cake'},
    {id:43,path:'../Images/AlmondPlaincake.jpeg',name:'Blueberry Cheese Cake',price:'600',type:'Cake'},
    {id:44,path:'../Images/CheesePlaincake.jpeg',name:'Plum Cake(No alcohol)',price:'600',type:'Cake'},
    {id:44,path:'../Images/CheesePlaincake.jpeg',name:'Mango Cake',price:'400',type:'Cake'},

]
export default imagesinfo